### ISSUE TITLE
Does the plugin support SonarQube 8.3?

### ISSUE THREAD

**Issue by Shweta-Deshpande** [sonar-perl/sonar-perl#109]
Hi 
Our team is experiencing an issue when running the plugin during scan:
java.lang.IllegalArgumentException: Unable to highlight file

Does the plugin support SonarQube 8.3? We are using that version and I was wondering if that is the issue.

Thanks and Regards,
Shweta

**Comment by otrosien** [comment]
Hi, the plugin is not yet compatible with SonarQube 7 and 8. I'm working on a fix here: https://github.com/sonar-perl/sonar-perl/pull/113

**Comment by otrosien** [comment]
Current master is compatible with SonarQube 7.9 and 8.6. I will test a bit more, and create a new release in the next days. If you want to play around, just build the plugin jar locally and install it into your SonarQube.

**Comment by otrosien** [comment]
Please try the latest version (0.5.2) and re-open if you see issues.
