### ISSUE TITLE
Failures with "Cannot register highlighting rule for characters at as it overlaps at least one existing rule"

### ISSUE THREAD

**Issue by rikbsd** [sonar-perl/sonar-perl#111]
It may also relate to issues #100 #103 #105 , but described there case is just a log.warn("Error highlighting token in file: "), not really a failure.

There is two problems that leads to the "overlap" bug.  In my case the problem started at HeredocChannel in colaboration with PODChannel: if you have a POD inside HereDoc - the end of heredoc will bu consumed by pod and the state of HeredocChannel will be saved for future files to analyze.

In most of the cases you will get a comment at the beginning of the file, that will initialize trivia structure, next you will hit HeredocChannel in incorrect state, so you will get an exception, that would be intercepted and ignored. The process begun. Next comment will be added to the trivia that was not reset due to exception and so on.

Once you get POD file, you will get a large virtual comment file inside trivia that with high probability overlaps with your code.

So we have two bugs, one in lexer, which is not resetted from file to file, and two bugs in HeredocChannel which also doesn't do reset between to files, and incorrect handling of PODs inside heredoc.

The provided patch solves only part of problem.  It tries to ignore incorrect heredoc state, and tries to reset the lexer state by anylizing the simple correct string after the failure, which is also lead to heredoc reset:
[heredoc_trivia_reset_patch.txt](https://github.com/sonar-perl/sonar-perl/files/5705084/heredoc_trivia_reset_patch.txt)

**Comment by otrosien** [comment]
Hi rikbsd, thanks for the patch. I'll take a look at it. Can you also provide some sample perlcode that triggers this error?

**Comment by otrosien** [comment]
I'll try to extract that from your comment but it would be easier if I had a concrete example.

**Comment by rikbsd** [comment]
It is fun, but the code that originally triggered the issue was perl source code itself.
