### ISSUE TITLE
Version 0.5.2 requires Java 11

### ISSUE THREAD

**Issue by amottier** [sonar-perl/sonar-perl#117]
Moving from 0.4.6 to 0.5.2 I realized that Java 11 is now required to execute Perl plugin for SonarQube.

This does not seems coherent with the official support of version 7.9 LTS as the [documentation of this version](https://docs.sonarqube.org/7.9/requirements/requirements/#header-3) mention that scanners can be executed with Java 8.

I understand that this might only apply to "official" plugins from SonarSource but I think it would be nice if Perl plugin can keep this compatibility until the end of 7.9 support.

**Comment by otrosien** [comment]
Hi @amottier, thanks for noticing. I will downgrade the JDK again with the next release.

**Comment by otrosien** [comment]
Hey @amottier, actually only SonarScanner can run on JDK8, the server side requires JDK11. I need to be consistent here, so that's why I cannot support JDK8 anymore.

**Comment by amottier** [comment]
> Hey @amottier, actually only SonarScanner can run on JDK8, the server side requires JDK11. I need to be consistent here, so that's why I cannot support JDK8 anymore.

I'm not sure to fully understand. As far as I know building the plugin targeting Java 8 should allow successful execution on both Java 8 and Java 11. 

From build log, the failure seems to be caused by running the server required by integration tests with Java 8.
I guess that `.travis.yml` and `its/plugin/build.gradle` (that is used only to run integration test) should still reference Java 11 but that `sonar-perl-plugin/build.gradle` should reference Java 8.

Maybe I can give it a try and do a pull request.

**Comment by otrosien** [comment]
Thank you for the contribution!

**Comment by amottier** [comment]
@otrosien Thanks for the release of version 0.5.3, I confirm that it run successfully with Java 8 :+1:
