### ISSUE TITLE
sonar-perl does not support java  Java 1.8.0_291

### ISSUE THREAD

**Issue by sdindiver** [sonar-perl/sonar-perl#122]
Hi,
I am trying to connect sonarqube server 
    mvn  sonar:sonar -Dsonar.host.url=https://sonarqube.rosetta.xyz.com/ -Dsonar.login=2faac6496bdc1fd95bae687461d7b8c24d90f008 -Djavax.net.ssl.keyStore=C:\Users\ECHADIK\.config\edpctl\auth\client.pkcs12 -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=Diksha@2809

but Its giving me below error
**Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project fdp: The plugin [perl] does not support Java 1.8.0_291: com/github/sonarperl/PerlPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 -> [Help 1]**

sonarqube server version is 8.7.1 that is running and I am using jdk1.8

but in similar manner If I use 8.9.1 on as local server using mvn sonar:sonar. Its working fine without any issue. 

I need support why do I need perl plugin for java project. I can not change jdk version of project. Do we have workaround for it?

**Comment by amottier** [comment]
The Perl SonarQube plugin is probably installed on your server. As far as I understand, even if not required when processing a Java project, SonarQube Maven plugin will execute, I guess, all SonarQube plugins installed on the server (I assume this is only to get some metadata about the SonarQube plugins).

A solution might be to uninstall the Perl plugin from your SonarQube server if you don't need it.

But if you need the Perl plugin to process other projects, I recommend to make sure (go to https://your-server-hostname/admin/marketplace) that you are using the latest version of Perl plugin (`0.5.3`) that is compatible with Java 8.

**Comment by otrosien** [comment]
Thanks for supporting @amottier, will close this as stale issue.
