### ISSUE TITLE
.cgi files are not getting scanned for violation

### ISSUE THREAD

**Issue by viks113** [sonar-perl/sonar-perl#124]

**Comment by otrosien** [comment]
Hi @viks113,

if you add cgi to the perl file extensions in settings, this should work. If not, please be more specific what you tried and what failed.

![Screenshot 2022-04-11 at 18 26 03](https://user-images.githubusercontent.com/129439/162894127-aeccd2b9-1c05-4e25-8a5c-ad6f55357844.png)
