### ISSUE TITLE
Not able to install sonar-perl-plugin-0.5.3-all.jar plugin on SonarQube-Version 9.1

### ISSUE THREAD

**Issue by rajagspann** [sonar-perl/sonar-perl#127]
Hi Team,

I did download the latest sonar-perl plugin from the link- https://github.com/sonar-perl/sonar-perl/releases/tag/0.5.3

Tried to install(manually) this in our dev-sonar instance. 

Manual installing plugins process:
1. Downloaded the perl plugin(sonar-perl-plugin-0.5.3-all.jar).
2. Put the downloaded jar in "$SONARQUBE_HOME/extensions/plugins"
3. Restarted SonarQube service.

But, the SonarQube service is not starting(Starting and immediately stopped).

NOTE: We are installing this perl plugin first time

Please find the logs below:
------------------------------
--> Wrapper Started as Daemon
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2022.02.03 02:34:33 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /sonar_home/temp
2022.02.03 02:34:33 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: IP:9001, TCP: IP:43212]
2022.02.03 02:34:33 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/sonar_install/sonarqube-9.1.0.47736/elasticsearch]: /sonar_install/sonarqube-9.1.0.47736/elasticsearch/bin/elasticsearch
2022.02.03 02:34:33 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2022.02.03 02:34:48 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2022.02.03 02:34:48 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/sonar_install/sonarqube-9.1.0.47736]: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/sonar_home/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Xmx1G -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-9.1.0.47736.jar:/sonar_install/sonarqube-9.1.0.47736/lib/jdbc/mssql/mssql-jdbc-9.2.0.jre11.jar org.sonar.server.app.WebServer /sonar_home/temp/sq-process2493683711908262098properties
2022.02.03 02:35:01 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2022.02.03 02:35:01 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2022.02.03 02:35:01 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2022.02.03 02:35:01 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
------------------------------

Please advise the solution for the same.

Regards,
Raja,

**Comment by rajagspann** [comment]
Hi Team,

Can someone help us on the above issue.

Regards,
Raja,

**Comment by slaffka-vlasov** [comment]
the same behavior is for SonarQube v9.3

**Comment by otrosien** [comment]
Hey everyone. Just wanted to let you know, I'm currently looking into this.

**Comment by otrosien** [comment]
There's a [new release](https://github.com/sonar-perl/sonar-perl/releases/tag/0.5.4) where we upgraded the baseline to the 8.9 LTS version. The integration tests also passed against 9.4, so I'm fairly confident that it also works. Please reopen if you see any issues.
