### ISSUE TITLE
sonar-perl 0.56.0 nor 0.60.0 are recognized in SonarQube 10.6.1

### ISSUE THREAD

**Issue by kirkpabk** [sonar-perl/sonar-perl#150]
Adding the plugin, I see that a tab appears, Sonar Community Perl.  We see the default report location of:  perlcritic_report.txt
We have perl::critic running correctly (with --cruel, in fact), we get a good 100K file with output.

However, when running a scan, we see no Perl sensor being detected.  We should see debug message like this in our pipeline output:

```
INFO: Quality profile for perl: Sonar way
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=27ms
INFO: Sensor Perl Squid Sensor [perl]
INFO: Sensor Perl Squid Sensor [perl] (done) | time=1686ms
INFO: Sensor Perl 5 Sensor [perl]
INFO: Sensor Perl 5 Sensor [perl] (done) | time=489ms
INFO: Sensor PerlCritic Sensor [perl]
INFO: Configured report path: Optional[perlcritic_report.txt]
INFO: PerlCritic report file 'perlcritic_report.txt' does not exist. Skipping...
INFO: Sensor PerlCritic Sensor [perl] (done) | time=6ms
```

But we see none of this... nothing for "perl" at all.   What would cause this?   Are others seeing this?  Just seems like the plugin is not picking up the perlcritic_report.txt in the root directory of the build pipeline.

Thanks in advance!

**Comment by otrosien** [comment]
Please try the latest sonar-perl release (0.6.2), and reopen this thread if you still have issues.
