### ISSUE TITLE
CVEs with yamlbeans and apache.commons:commons-compress 

### ISSUE THREAD

**Issue by razac05** [sonar-perl/sonar-perl#154]
Trivy is reporting 4 CVEs (2 High/2 Medium) on the versions of com.esotericsoftware.yamlbeans:yamlbeans and org.apache.commons:commons-compress. Both libraries have remediated versions available:

| Library | Current Version | Remediated Version |
| --- | --- | --- |
| com.esotericsoftware.yamlbeans:yamlbeans | 1.15 | 1.17 |
| org.apache.commons:commons-compress | 1.24.0 | 1.26.0 |

[trivy_report_sonar-perl-plugin.txt](https://github.com/user-attachments/files/17978878/trivy_report_sonar-perl-plugin.txt)

**Comment by otrosien** [comment]
Novelty for this project: Two releases a day. 😅
