### ISSUE TITLE
read the header of the file when then are not ending in a known suffix

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [sonar-perl/sonar-perl#39]
Hello,

i have a case in our project Argonaut https://github.com/fusiondirectory/argonaut that the main programs are not ending in .pm or .pl etc.. so perlcritic find the issues but the sonar-perl scanner doesnt report them to sonar.

it would be nice that if the perl scanner encounter a file without an extension it read the header of the file and try to fin if there is a #!/usr/bin/perl at the beginning of the file so the result of this file could be send to sonar

i attach the perlcritic file and the output of the jenkins running the sonnar scanner

Thanks and happy new year !
[perlcritic.txt](https://github.com/otrosien/sonar-perl/files/679976/perlcritic.txt)
[sonar-perl-jenkins.txt](https://github.com/otrosien/sonar-perl/files/679977/sonar-perl-jenkins.txt)

**Comment by otrosien** [comment]
Hi,

I don't think it is a good idea, performance-wise. It also does not follow common SonarQube practice. Do your files have no filename extension at all? Or is it just a different one than the usual? In the latter case, just add those extensions to `com.github.otrosien.sonar.perl.suffixes` config property.

**Comment by otrosien** [comment]
According to http://docs.sonarqube.org/display/SONAR/Analysis+Parameters there's also `sonar.import_unknown_files` - might help when attaching perlcritic issues to those files, but I haven't tested that.

**Comment by bilbo-the-hobbit** [comment]
hello,

no they don't have any extension, but i will test with this sonar.import_unknown_files it seems to be easier don't now if we can do that by project 

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

i have tested and that configuration work perfectly on my sonar-scanner inside jenkins

sonar.import_unknown_files=true

sonar.exclusions=READ*,Change*,COPY*,AUTH*,perlcritic_report.txt

maybe we could a a paragraph about this in the documentation ?

Cheers

**Comment by otrosien** [comment]
Sounds good. Mind to give it a try?
