### ISSUE TITLE
Recognize code duplications

### ISSUE THREAD

**Issue by otrosien** [sonar-perl/sonar-perl#42]
How? To be figured out. Either there is a perl util that is able to produce a decent report, or we need to wait until we can properly parse perl code.

**Comment by Ko1203** [comment]
We are new for SonarQube and share the sample for Deduce Code Duplication for PERL programming.

**Comment by otrosien** [comment]
Hi Ko1203,

the feature of recognizing code duplications is not implemented yet. That's why this issue is still open. If you're interested, I'd be happy to accept contributions.

**Comment by otrosien** [comment]
As a first shot we'll try to integrate Copy-paste-detection via PMD. ( see https://github.com/sonar-perl/sonar-perl/issues/62 )

**Comment by otrosien** [comment]
CPD is coming with the next release.
