### ISSUE TITLE
Integration in SonarQube.com and plugin version matrix

### ISSUE THREAD

**Issue by vhamon** [sonar-perl/sonar-perl#44]
There is many plugins available in sonarqube.com, but unfortunately sonar-perl is not in there. 
Furthermore, sonar-perl is not in the official plugin version matrix, and it's a pity : 
https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

Because I work in a open source project, sonarqube.com is for us a free and convenient solution.
I think it could increase your plugin's visibility. Is there anything I can do for it ?

**Comment by otrosien** [comment]
@vhamon thanks for reaching out. sonar-perl is listed under "Other plugins" on the sonarqube wiki ( https://docs.sonarqube.org/display/PLUG/Other+Plugins ), and as far as I know sonarsource sets high standards if you want to get listed on the plugin portal, and it's even harder to get installed on sonarqube.com. 

But adding sonar-perl to the matrix is low-hanging fruit. If you want to offer your help, that would be nice of you to do so. We support LTS 5.6 and 6.x.

What I can offer is putting your project on our hosted version of sonar-perl on http://sonarqube.racodond.com which is run by @racodond, a freelance QA consultant.

**Comment by racodond** [comment]
@vhamon @otrosien For your information, SonarSource doesn't want non-SonarSource plugins to be hosted on sonarqube.com. That's one of the reasons, I built my own platform. And sure, feel free to host your project on my platform.

**Comment by vhamon** [comment]
Okay, I understand now. And yes, I would like to contribute on that plugin. Could you please tell me how I can proceed in order to add my project on your platform ?

**Comment by otrosien** [comment]
@vhamon please get in touch with @racodond to get an account on his hosted platform.

**Comment by otrosien** [comment]
I'll close this ticket for now.
