### ISSUE TITLE
Update the link on Sonarqube site's "Other Plugins" list

### ISSUE THREAD

**Issue by stphnlyd** [sonar-perl/sonar-perl#45]
On https://docs.sonarqube.org/display/PLUG/Other+Plugins it's pointing to https://github.com/otrosien/sonar-perl instead of https://github.com/sonar-perl/sonar-perl

Can someone update that?

**Comment by otrosien** [comment]
Thanks for pointing out. I notified SonarSource, they'll take care of updating the link.
