### ISSUE TITLE
Can we also support TAP::Harness::JUnit for test reporting

### ISSUE THREAD

**Issue by stphnlyd** [sonar-perl/sonar-perl#46]
At my workplace we defaultly use TAP::Harness::JUnit. As this plugin now consumes TAP::Harness::Archive report, for Sonarqube we would need to run the tests for a second time, which is inconvenient and time-wasting. So I wonder if it's possible to support TAP::Harness::JUnit.

**Comment by otrosien** [comment]
Thank you for filing a feature request. Do you want to give a try at implementing something as a PR?
