### ISSUE TITLE
Support SonarQube 6.3 / 6.4

### ISSUE THREAD

**Issue by otrosien** [sonar-perl/sonar-perl#55]
SonarQube 6.4 drops a deprecated API, which makes SonarPerl incompatible with that version for now. Probably related to issue #20.

**Comment by otrosien** [comment]
Started cross-version testing. Current range is `[5.6;6.2]`. `6.3.1` seems to run in docker, but the integration tests fail with NPE. Needs further investigation.

**Comment by souadghiri** [comment]
@otrosien  I'm no PERL expert (at all), but I use Sonar 6.4 and was hoping to use your plugin. If I can help, let me know! Else I can be an average mental cheerleader. Good luck with this 🤞!

**Comment by drmmr763** [comment]
Just want to add in that I'm experiencing this issue now. The sole reason I'm implementing SonarQube is for this plugin so I will downgrade to the 5.6.7 LTS for now, but would love to see this issue fixed. Willing to help test

**Comment by otrosien** [comment]
Hi @drmmr763 I'm currently stuck at figuring out the root cause of the NPE in the integration test. If you have spare resources, I would appreciate help in that regard.

**Comment by drmmr763** [comment]
Hi @otrosien 

I'm definitely interested in helping with this. I will admit, I'm not into java so I'm gonna be a little slow getting up to speed. Here's where I'm at:

- running OSX
- I installed Java 8
- installed gradle via homebrew
- cloned sonar-perl
- ran `./gradlew build`

I got this error during the build:
```
com.github.sonarperl.it.IntegrationTests > classMethod FAILED
    java.lang.NoClassDefFoundError

1 test completed, 1 failed
:it-perl-plugin:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':it-perl-plugin:test'.
> There were failing tests. See the report at: file:///Users/cwindnagle/Projects/sonar-perl/its/plugin/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.047 secs
```

I did try running the stack trace and debug options but the output is pretty substantial and I'm not sure how helpful. this doesn't seem to be the same null pointer exception you were talking about. Did I miss a piece or is this the problem we're trying to solve? 

I see you mentioned here something about the Orchestrator object needing some review (https://github.com/sonar-perl/sonar-perl/pull/58#issuecomment-330079811) is that also a part of this issue?

Side note: I see that just 2 days ago the Orchestrator class was updated by the Sonar team to revert some functionality to 5.6:

https://github.com/SonarSource/orchestrator/commit/4e7535dc56acd21456770bd530bb93e5e6c5451b

Could that also be related?

**Comment by souadghiri** [comment]
@otrosien don't know if this will help, but the owasp project lately received a PR that allowed them to be compliant with SonarQbe 6.3 (I did not tested it yet, but the PR was approved).

[The issue](https://github.com/stevespringett/zap-sonar-plugin/issues/7), its key comment:

> Now that an updated version of the Dependency-Check SonarQube plugin has been released that supports SQ 6.3 and higher, the ZAP plugin should be updated in much the same manner.

And [the submitted & approved PR](https://github.com/stevespringett/zap-sonar-plugin/pull/9)

Hope this can help.

**Comment by otrosien** [comment]
Thanks for the hint. The PR is pretty big so at first glance I don't see any correlation to our problem. Ultimately someone needs to implement a proper parser (see issue #6), but this is too much effort for only showing some syntax highlighting.

I do like the idea of ignoring the CodeHighlighting on newer versions for now, which is what's already merged. But I can't release at the moment because of this NullPointerException which either means we need to fix some more things to support SonarQube 6.4+ or it may require just a small fix in the test code.

**Comment by souadghiri** [comment]
Got it. I'll try to take time to see if I can understand where the NPE comes from :|. If I have ideas, I'll let you know.

**Comment by souadghiri** [comment]
@otrosien before and after the orchestration version update, the only failure I have is: éCalculate task graph".
![image](https://user-images.githubusercontent.com/28731357/32775475-d0874206-c92f-11e7-9db9-50f8f18355ea.png)

**Comment by otrosien** [comment]
I'm about to get this fixed... Expect a release shortly.

**Comment by otrosien** [comment]
Try release 0.3.2
