### ISSUE TITLE
Regarding perl- sonar duplications

### ISSUE THREAD

**Issue by SubhashiniRavichandran** [sonar-perl/sonar-perl#59]
#42 Hi friends,
I just trying to get the duplications to be displayed ,even though if we push the Perl code with duplications I get no duplication indication with the sonar .Please assist me so that I can get the duplications need to be displayed on viewer side .Thanks in advance!

**Comment by SubhashiniRavichandran** [comment]
> Help wanted

**Comment by otrosien** [comment]
Hi SubhashiniRavichandran,

the feature of recognizing code duplications is not implemented yet. That's why issue #42 is still open. If you're interested, I'd be happy to accept contributions.

**Comment by SubhashiniRavichandran** [comment]
Thanks for sharing , we are working on it ,once if we get some clarity we'll share our points with you for sure

**Comment by otrosien** [comment]
As a first shot we'll try to integrate Copy-paste-detection via PMD. ( see https://github.com/sonar-perl/sonar-perl/issues/62 )

**Comment by otrosien** [comment]
CPD is coming with the next release.
