### ISSUE TITLE
Support SonarQube 6.7 LTS - Perl plugin 0.3.1

### ISSUE THREAD

**Issue by Ko1203** [sonar-perl/sonar-perl#60]
We have upgraded the SonarQube 6.7 LTS in my UAT environment but we unfortunately we are facing issue for Perl platform. 

**Error Log**:
Background initialization failed. Stopping SonarQube java.lang.IllegalStateException: Fail to load plugin Perl [perl] 

Kindly advise.

**Comment by Ko1203** [comment]
@otrosien ~ Kindly let us know any changes need to be done from my end. Thank you in advance.

**Comment by souadghiri** [comment]
@Ko1203 I guess first we need to solve https://github.com/sonar-perl/sonar-perl/issues/55 :|

**Comment by Ko1203** [comment]
@souadghiri ~ Thank you for your email and i agree for your point. Thanks again.

**Comment by otrosien** [comment]
I'm about to get this fixed... Expect a release shortly.

**Comment by otrosien** [comment]
Try release 0.3.2

**Comment by Ko1203** [comment]
@otrosien ~ I confirmed the Perl plugin 0.3.2 got supported for SonarQube 6.7. Thank you very much for your support on behalf of my team/organization.

**Comment by drmmr763** [comment]
Just curious to know if anyone has tried 7.0 yet ?

**Comment by otrosien** [comment]
I'll add an issue for this.
