### ISSUE TITLE
Import PMD CPD report (xml) to SonarQube system

### ISSUE THREAD

**Issue by Ko1203** [sonar-perl/sonar-perl#62]
@otrosien and @all ~ We have generated the Code duplication report using PMD application. kindly advise, if we can able to an import the report (xml) to SonarQube system then i will share the our java code for your review.

_Sample files attached for your review:_
[Project3.zip](https://github.com/sonar-perl/sonar-perl/files/1565864/Project3.zip)

**Comment by otrosien** [comment]
Hi @Ko1203, very interesting results. How did you plug into PMD? Doesn't it require a perl parser?

**Comment by Ko1203** [comment]
Hi @otrosien ~ We are glad to share our experience what we gained and achieved in code duplication in PERL programming
- Execute the PMD-CPD report and save the report as XML (Name follow our own) in our project.
- There is no Perl parser required
- Kindly provide the option to import the PMD-CPD report to SonarQube using our Sonar-perl plugin 

P.S. : Currently we are generate the Perl::Critic and PMD-CPD reports via PERL script

```PMD CPD Reference: https://pmd.github.io/pmd-5.4.1/usage/cpd-usage.html```

**Comment by otrosien** [comment]
@Ko1203, have you checked if it's possible to use the off-the-shelf plugin for PMD? ( https://github.com/SonarQubeCommunity/sonar-pmd )

**Comment by Ko1203** [comment]
@otrosien ~ thank you for sharing the information. We will do some exercises with sonar-pmd plugin and share our results.

**Comment by Ko1203** [comment]
Hi @otrosien  ~ Thank you for your information. Kindly clarify the sonar-pmd and pmd-cpd are identical? 

```
sonar-pmd  : Code Quality plugin which the coding ruleset defined
pmd-cpd    : Finding duplicate code
```
We request perl user can share the pmd-cpd report (xml) to sonr-plugin like Perl::Critic report.  we can try to import the CPD report to SonarQube dashboard.

**Comment by Ko1203** [comment]
@otrosien ~ we will do some exercises with sonar-pmd plugin and we will share our results .

**Comment by Ko1203** [comment]
Hi @otrosien  I have checked the sonr-pmd plugin but it's not satisfied with our requirement.

FYI:- I tried with sonar-cpd plugin but unfortunately the plugin not  support SonarQube 6.7. 

Kindly advise.

**Comment by otrosien** [comment]
Hi, 
pmd-cpd - I can't even find infos about who implemented that originally, because one possibility could be to make it sonar 6+ compatible. Can you clarify some details on your experience with sonar-pmd? Was it missing code duplication functionality or an xml-import or something else?

**Comment by Ko1203** [comment]
Hi @otrosien ~ we are using sonar 6.7.1 and the code duplication function not supported for **Perl programming** when we are use the sonar-pmd plugin. Kindly let us know , how to proceed. 

Thank you !!

We tried with sonar-cpd plugin but it shows error message (attahced) [sonar-cpd.txt](https://github.com/sonar-perl/sonar-perl/files/1582489/sonar-cpd.txt)

**Sonar-PMD**
 ```
17:27:47.839 INFO: Sensor CPD Block Indexer
17:27:47.841 DEBUG: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer is used for perl
17:27:47.844 DEBUG: No CpdMapping for language perl
17:27:47.846 INFO: Sensor CPD Block Indexer (done) | time=7ms
```

**Comment by otrosien** [comment]
Thanks for the details. From what I've seen this basically leaves us with the option to write a custom XML importer to convert that CPD XML into SensorContext#newCpdTokens() -- do you want to give it a try?

**Comment by otrosien** [comment]
https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/cpd/XMLRenderer.java -- if I'm not mistaken, then this is the XML format produced by PMD.

**Comment by Ko1203** [comment]
Thank you for your support @otrosien and I will come back with better result for the CPD for the Perl Programming.

**Comment by Ko1203** [comment]
Hi @otrosien

 **I hope 2017 have gone greatly for you and I wish you to achieve all the Success in 2018.** 

We tried your suggestion of CPD XML rendering but we are unable to complete the task from our end. if possible can you share the sample cpd.xml file.

I would like to bring in to you notice the CPD mapping is not added for PERL programming in SonarScanner.
```
- 16:55:35.730 INFO: Sensor PerlCritic Sensor [perl] (done) | time=326ms
- 16:55:35.732 INFO: Sensor Zero Coverage Sensor
- 16:55:35.745 INFO: Sensor Zero Coverage Sensor (done) | time=13ms
- 16:55:35.748 INFO: Sensor CPD Block Indexer
- 16:55:35.749 DEBUG: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer is used for perl
- 16:55:35.751 DEBUG: **No CpdMapping for language perl**
- 16:55:35.752 INFO: Sensor CPD Block Indexer (done) | time=4ms
- 16:55:35.766 INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
- 16:55:35.770 INFO: Calculating CPD for 0 files
- 16:55:35.772 INFO: CPD calculation finished
```

**Comment by otrosien** [comment]
now that we a parser, we could actually look into integrating copy-paste-detection from PMD.

Links:
* https://github.com/search?q=org%3ASonarSource+Cpd&type=Code
* https://github.com/SonarSource/sonar-go/blob/c052e8c3530f00a3963eaa7b79e801382d808f0d/sonar-go-plugin/src/main/java/org/sonar/go/plugin/CpdVisitor.java
* https://github.com/SonarSource/sonar-python/blob/master/sonar-python-plugin/src/main/java/org/sonar/plugins/python/cpd/PythonCpdAnalyzer.java

I'll try to come up with something in the next days. Might turn out that our parser is too rudimentary, though.

**Comment by rbay85** [comment]
Hi @otrosien 

Based on sonar-phyton, sonar-c++ and  sonar-bsl plugins I write PerlCpdAnalyzer.class and seems managed to get Code Duplication on our SonarQube server for our Perl project
![image](https://user-images.githubusercontent.com/22322335/64517965-faec7180-d2f9-11e9-8a1d-db97b50d7666.png)

waiting for feedback from our Perl team..

**Comment by otrosien** [comment]
CPD is coming - after a long time waiting - with the next release.
