### ISSUE TITLE
Support new rules

### ISSUE THREAD

**Issue by drmmr763** [sonar-perl/sonar-perl#67]
Hi!

As always thanks for this great plugin. I have a new rule I'd like to add to the rules database. I can send a PR with the updated XML if you need. The rule I want is:

https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::PreventSQLInjection

But I was thinking if it would be possible to be able to make rules a little more flexible for when custom ones are needed.

Maybe on the SonarQube Perl settings page, we could add a file inclusion to a new XML which is then merged? My thinking this would allow custom rules to be added as needed and also prevent the need for a whole sonar-perl release each time a new rule is added to the database. 

Chad

**Comment by otrosien** [comment]
Hey Chad,

thanks for your feedback. Uploading an XML via webform sounds rather strange I would say. What about being able to apply custom rules when running the sonar scanner? It might even be possible already...

**Comment by drmmr763** [comment]
That could work. The only reason I suggested the XML route was I assumed that the XML list was what SonarQube used to generate it's "rules" list of filters in Sonar's interfaces.

Would applying custom rules during scanning allow you to see the rules in Sonarqube and filter by them and all that? If so that sounds like a reasonable solution to me for sure.

**Comment by otrosien** [comment]
It's been too long since I tried, but I remember something like a custom rules profile other than the "Sonar way", and then you include custom rules alongside. But I will need to double-check.

**Comment by otrosien** [comment]
This sounds like extra coding effort. I was thinking about uploading an extended rules xml file into sonarqube, but not through web ui, but through the command-line.

https://github.com/sonar-perl/sonar-perl/blob/master/sonar-perl-plugin/src/main/resources/com/github/otrosien/sonarperl/perlcritic-rules.xml

**Comment by otrosien** [comment]
Hey Chad,

I'm back on the project now. I'll try and see what can be done in order to support custom perlcritic rules.

**Comment by willt** [comment]
Any word on this?

**Comment by drmmr763** [comment]
Not that I've seen no. I still use SonarPerl but also check for various violations within jenkins directly to ensure I'm covering everything I need.

**Comment by otrosien** [comment]
Sorry, haven't been spending much time on the project lately. Now that we're back on the latest version, I'll take another look.

**Comment by otrosien** [comment]
We will start supporting unknown perlcritic rules in the next release. https://github.com/sonar-perl/sonar-perl/pull/139

**Comment by dineshyagappan** [comment]
@otrosien  - How do we add new Perl critic rules ? . For example https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::PreventSQLInjection
