### ISSUE TITLE
Sonar Perl not able to analyse my project

### ISSUE THREAD

**Issue by ellurukalyan** [sonar-perl/sonar-perl#68]
I have Installed Sonar-perl Plugin and analysed the code. It is showing only codesmell but not able to find the bugs or Vulnerabilities. I have even tried even the example shown cover.pm still it is not showing the bugs/Vulnerabilities. Please help me in resolving this issue

**Comment by otrosien** [comment]
Did you follow the guide https://github.com/sonar-perl/sonar-perl#analyzing-your-perl-project ? You need to provide the perlcritic analysis report like described in the README.

**Comment by ellurukalyan** [comment]
Its working fine now. Thanks otrosien :)

**Comment by otrosien** [comment]
👍

**Comment by ymakkapati** [comment]
I pulled sonarperl image from docker hub and ran container. Installed sonar-scanner from the container, I have the same issue as above. I read your github instructions for perl_critic but get the error "perlcritic command not found", when I try to run "perlcritic --cruel --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" lib t"

**Comment by ymakkapati** [comment]
I am running your sonar perl container. Does not your container comes with perlcritic. Do I have to install it on container

**Comment by otrosien** [comment]
yes, sonar-perl doesn't come with perlcritic. You need to run it on your own and provide the results to the sonar-scanner.
