### ISSUE TITLE
SonarQube v7 Developer Edition

### ISSUE THREAD

**Issue by drmmr763** [sonar-perl/sonar-perl#91]
Has anyone used SonarPerl with SonarQube Developer edition?

I'm assuming SonarPerl is compatible with SonarQube 7 as there is a release around that. Beyond that though, do the Developer edition features like PRs / multi branch etc.. function as one would expect with Perl code bases?

Thanks for any insight that can be shared!

**Comment by otrosien** [comment]
Hi, I haven't tried but the plugin doesn't make any assumptions with regards to branches etc, so I don't see why it should not work. If you want, please try and share your experience.

**Comment by drmmr763** [comment]
Thanks for the answer. We might give it a shot. Gonna try to upgrade to version 7 here soon.
