### ISSUE TITLE
unable to highlight file

### ISSUE THREAD

**Issue by jharris-tc** [sonar-perl/sonar-perl#92]
Hi, I am using sonarperl 0.4.5, SonarQube 7.5 Community Edition, Sonar Scanner 3.3.0.1492

I am having an issue analyzing a perl project. I have taken out a bunch of stuff but this code

```#!/usr/bin/perl

my ( $file );

usage() if not ( $file );

sub usage {
    print <<EOTEXT;
Usage: $0 --file=<filename>
EOTEXT

    exit 1;
}
```

still triggers error: 
"ERROR: Error during SonarQube Scanner execution
ERROR: Unable to highlight file $thefile
ERROR: Caused by: 6 is not a valid line offset for pointer. File $thefile has 0 character(s) at line 11"

for the record, line 11 is the  blank line before exit 1. If that line is removed, I get this error :
"ERROR: Error during SonarQube Scanner execution
ERROR: Cannot register highlighting rule for characters at Range[from [line=11, lineOffset=4] to [line=11, lineOffset=8]] as it overlaps at least one existing rule"

**Comment by otrosien** [comment]
Thank you for the bug report. I'll investigate.

**Comment by jharris-tc** [comment]
hey, so I've started to look at this and it seems from both [here](http://sonarqube-archive.15.x6.nabble.com/Cannot-register-highlighting-rule-for-characters-td5029735.html), and tinkering. that the issue is being caused by the term "exit" being attached to two rules instead of one.

In the url I linked, the default keyword was being viewed as both a keyword and a modifier of the next word so it was attached to two  highlight rules (might not be totally correct on this)

Currently, exit is 4 spaces out (convention), but if I make it 0 spaces or 1 or 2 spaces it works fine. 3, 4 or 5  spaces throw the highlighting error, and any more spaces than that also word fine without the error.

I'm trying to figure out what the other highlighting rule could be. I'm guessing maybe it has something to do with the print statement highlighting rules?

Any advice on where to proceed from here would be great, I know you're busy but I would very much like to fix this. Thanks.

**Comment by otrosien** [comment]
Thanks for coming back to me with details. It's probably because of the heredoc statement which was a bit tricky to implement.

**Comment by otrosien** [comment]
@jharris-tc I merged a fix into master and will release within the next days. There will be a new docker image uploaded to the latest tag here: https://hub.docker.com/r/sonarperl/sonar-perl/tags 
If you want to give it a spin, that would be great.

**Comment by jharris-tc** [comment]
tested this fix with the newest docker image and it worked! thank you. There is another issue though, but I will create that shortly :)
