### ISSUE TITLE
Highlighting Error: not a valid line for pointer

### ISSUE THREAD

**Issue by jharris-tc** [sonar-perl/sonar-perl#96]
when running sonar-perl against this file (text replaced):
```
#!/usr/bin/perl

use strict;

sub usage {
    print <<EOF;
Usage: $0

Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum

EOF

    exit;
}
```

I get this error:
java.lang.IllegalArgumentException: Unable to highlight file $file
Caused by: java.lang.IllegalArgumentException: 27 is not a valid line for pointer. File $file has 21 line(s)

I haven't exactly been able to figure out what is causing it, but I do know it depends on the amount of lines. So for example, this:

```
#!/usr/bin/perl

use strict;

sub usage {
    print <<EOF;
Usage: $0

Lorem ipsum dolor sit amet, consectetur adipiscing elit,

EOF
    exit;
}
```

doesn't work,

but this 

```
#!/usr/bin/perl

use strict;

sub usage {
    print <<EOF;
Usage: $0

Lorem ipsum dolor sit amet, consectetur adipiscing elit,

EOF

    exit;
}
```

does work.

I have managed to find examples where a couple of lines worked, and some where they did not. I am not completely sure what is going on. All I have been able to figure out is that the amount of lines matters, and that the specific text does not.

**Comment by jharris-tc** [comment]
I tested this with:
INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 4.18.0-10-generic amd64

On the latest sonar-perl docker image as a server

**Comment by jharris-tc** [comment]
Just realized that this issue seems to be completely fixed in the previous version of sonar-perl

**Comment by otrosien** [comment]
Hi, with "previous version" you mean current master?

**Comment by jharris-tc** [comment]
sorry, I mean 0.45

**Comment by otrosien** [comment]
I did change multi-line regex ( https://github.com/sonar-perl/sonar-perl/blob/master/perl-frontend/src/main/java/com/github/sonarperl/lexer/HeredocChannel.java#L58 ) , and add a multi-line unit test ( https://github.com/sonar-perl/sonar-perl/blob/master/perl-frontend/src/test/java/com/github/sonarperl/lexer/PerlLexerTest.java#L176 ) in master, so it should be working now, but it probably wasn't the case in the 0.4.5 release.

**Comment by jharris-tc** [comment]
sorry, to be clear, this issue is ONLY on the current release (ie the 'latest' tag on the docker image), and it is NOT AN ISSUE in the '0.45' tag of the docker image

**Comment by otrosien** [comment]
interesting. Thanks for reporting. I'll investigate

**Comment by jharris-tc** [comment]
thank you

**Comment by otrosien** [comment]
please try again, I think it's fixed now.

**Comment by jharris-tc** [comment]
everything is working! Thanks so much man, if you're ever in Toronto I'll buy you a drink
