### ISSUE TITLE
Can not get code analysis working

### ISSUE THREAD

**Issue by wvankuyk** [sonar-perl/sonar-perl#99]
I am using:
- Sonarqube version:  7.2.1.14109 community edition
- Perl plugin version: 0.4.6
- Windows 2016
- IDE Intellij 2019.1.1 (which I did learn using the sonarlint pluggin doesnt use 3rd party plugins)

I try to initiate a scan with:
sonar-scanner -Dsonar.projectKey=perl_scripts -Dsonar.sources=. -Dsonar.language=perl

I get:
INFO: Scanner configuration file: D:\sonar-scanner-4.0.0.1744-windows\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 4.0.0.1744
INFO: Java 11.0.3 AdoptOpenJDK (64-bit)
INFO: Windows Server 2016 10.0 amd64
INFO: User cache: C:\Users\r611348\.sonar\cache
INFO: SonarQube server 7.2.1
INFO: Default locale: "en_US", source code encoding: "windows-1252" (analysis is platform dependent)
INFO: Publish mode
INFO: Load global settings
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/Users/r611348/.sonar/cache/b16b4fe54d9dfecea420156fa339f59f/sonar-scanner-engine-shaded-7.2.1-all.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO: Load global settings (done) | time=168ms
INFO: Server id: AWwHNtKsWnDSacnKnd5d
INFO: User cache: C:\Users\r611348\.sonar\cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=101ms
INFO: Load/download plugins (done) | time=173ms
INFO: Loaded core extensions:
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=18ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=48ms
INFO: Load active rules
INFO: Load active rules (done) | time=1294ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=42ms
INFO: Project key: perl_scripts
INFO: Project base dir: D:\RemoteRepos\Bill\perl_scripts
INFO: -------------  Scan perl_scripts
INFO: Load server rules
INFO: Load server rules (done) | time=394ms
INFO: Base dir: D:\RemoteRepos\Bill\perl_scripts
INFO: Working dir: D:\RemoteRepos\Bill\perl_scripts\.scannerwork
INFO: Source paths: .
INFO: Source encoding: windows-1252, default locale: en_US
INFO: Language is forced to perl
INFO: Index files
WARN: File 'D:\RemoteRepos\Bill\perl_scripts\_Deparsed_XSubs.pm' is ignored because it doesn't belong to the forced language 'perl'
INFO: 1 file indexed
INFO: Quality profile for perl: Sonar way
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=27ms
INFO: Sensor Perl Squid Sensor [perl]
INFO: Sensor Perl Squid Sensor [perl] (done) | time=1686ms
INFO: Sensor Perl 5 Sensor [perl]
INFO: Sensor Perl 5 Sensor [perl] (done) | time=489ms
INFO: Sensor PerlCritic Sensor [perl]
INFO: Configured report path: Optional[perlcritic_report.txt]
INFO: PerlCritic report file 'perlcritic_report.txt' does not exist. Skipping...
INFO: Sensor PerlCritic Sensor [perl] (done) | time=6ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=14ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=3ms
INFO: SCM provider for this project is: git
INFO: 1 files to be analyzed
INFO: 0/1 files analyzed
WARN: Missing blame information for the following files:
WARN:   * perl_scripts/validations.pl
WARN: This may lead to missing/broken features in SonarQube
INFO: Calculating CPD for 0 files
INFO: CPD calculation finished
INFO: Analysis report generated in 187ms, dir size=1000 KB
INFO: Analysis reports compressed in 110ms, zip size=210 KB
INFO: Analysis report uploaded in 255ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard?id=perl_scripts
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://localhost:9000/api/ce/task?id=AWwLERDtkqB_152AyYt1
INFO: Task total time: 8.486 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 11.533s
INFO: Final Memory: 12M/54M
INFO: ------------------------------------------------------------------------

but I see no code issues, when I know there are plenty.  What concerns me is :  INFO: 0/1 files analyzed

Am I doing something wrong?  Sonarqube does see the plugin and I can set certain settings, and I see all of the rules for perl, just no issues....?

**Comment by otrosien** [comment]
does your perl code show up in sonarqube? I think you're just missing the fact that sonar-scanner is not running perlcritic for you. Please follow the instructions from the README: https://github.com/sonar-perl/sonar-perl#analyzing-your-perl-project
